# Meta Data for SEO

## Homepage
title = "Githaxs"
titleSeparator = "-"
titleAddition = "CI as a Service"
description = "Githaxs provides CI as a Service so developers can focus their efforts on creating products instead of CI tools and pipelines."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = ""
twitterCreator = ""
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo.png"
schemaTwitter = "https://twitter.com/"
schemaLinkedIn = "https://www.linkedin.com/in/gabelevasseur/"
schemaGitHub = "https://github.com/githaxs"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Copyright &#169; 2021 All rights reserved to Githaxs."

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/githaxs/docs.githaxs.com"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
